apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
  - name: proxy
    image: ubuntu
    command:
    - sh
    - -c 
    - 'apt-get update && apt-get install iptables -y && iptables -L sleep 1d'
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
