apiVersion: v1
kind: Pod
metadata:
  name: busybox
  annotations:
    container.apparmor.security.beta.kubernetes.io/<container_name>: localhost/<apparmor_profilename>
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo "I write to the disk!" > diskwrite.log; sleep 5; done']
